# /home/github-actions/infrastructure/a1_api/docker-compose.yaml
services:
  api_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: infra-a1-api-service
    restart: always
    volumes: #Makes (private) config available to the image for loading secrets like the API key - alias mapping
      - ./api/config:/usr/src/app/config:ro
    environment:
      NODE_ENV: production
      #MONGO_USER and MONGO_PASSWORD set in .env (other values are also set there to override these during development)
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: a1_database
    depends_on:
      - db_service
    networks:
      - caddy_network
    labels:
      caddy: kit328.ict.utas.edu.au
      # Static route matching rule -- this path is permanently reserved
      caddy.handle_path: /a1_api*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 5000}}"

  db_service:
    image: mongo:7.0
    container_name: infra-a1-api-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - caddy_network
    # Explicitly do NOT expose ports to the host -- keeps the database internal to the mesh network

networks:
  caddy_network:
    name: caddy_network
    external: true

volumes:
  mongo_data:
    name: infra_a1_api_mongo_data